name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest

    - name: Run Docker container
      run: docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest

    - name: Run tests
      run: |
        # Add your test commands here, for example:
        curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:3000
        # You can also use any test scripts you have in your package.json
        # docker exec <container_id> npm test

    - name: Push Docker image
      if: github.ref == 'refs/heads/main'
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
